export const DepressedPhotos = [
  { src: "/witch-pages/depressed040/photos/aaba.jpg" },
  { src: "/witch-pages/depressed040/photos/aada.jpg" },
  { src: "/witch-pages/depressed040/photos/aadb.jpg" },
  { src: "/witch-pages/depressed040/photos/aadd.jpg" },
  { src: "/witch-pages/depressed040/photos/abac.jpg" },
  { src: "/witch-pages/depressed040/photos/abbb.jpg" },
  { src: "/witch-pages/depressed040/photos/abdd.jpg" },
  { src: "/witch-pages/depressed040/photos/adbb.jpg" },
  { src: "/witch-pages/depressed040/photos/adcb.jpg" },
  { src: "/witch-pages/depressed040/photos/bbcc.jpg" },
  { src: "/witch-pages/depressed040/photos/bccb.jpg" },
  { src: "/witch-pages/depressed040/photos/cabb.jpg" },
  { src: "/witch-pages/depressed040/photos/cbba.jpg" },
  { src: "/witch-pages/depressed040/photos/cbda.jpg" },
  { src: "/witch-pages/depressed040/photos/cbdb.jpg" },
  { src: "/witch-pages/depressed040/photos/ccab.jpg" },
  { src: "/witch-pages/depressed040/photos/ccac.jpg" },
  { src: "/witch-pages/depressed040/photos/ccbb.jpg" },
  { src: "/witch-pages/depressed040/photos/ccdb.jpg" },
  { src: "/witch-pages/depressed040/photos/cddb.jpg" },
  { src: "/witch-pages/depressed040/photos/dadc.jpg" },
  { src: "/witch-pages/depressed040/photos/dbba.jpg" },
  { src: "/witch-pages/depressed040/photos/dbca.jpg" },
  { src: "/witch-pages/depressed040/photos/ddbd.jpg" },
  { src: "/witch-pages/depressed040/photos/badb.webp" },
  { src: "/witch-pages/depressed040/photos/dbdc.webp" }
];